### ISSUE TITLE
Cannot import msg file (unknown location) 

### ISSUE THREAD

**Issue by yhjJean** [qq44642754a/Yolov8_ros#5]
I am facing the issue when launching the yolo_v8 launch file. It shows cannot import all the msg file. Any idea? Please help

Traceback (most recent call last):
  File "/home/user/catkin_ws/devel/lib/yolov8_ros/yolo_ros.py", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/user/catkin_ws/src/yolov8_ros/yolov8_ros/scripts/yolo_ros.py", line 14, in <module>
    from yolov8_ros_msgs.msg import BoundingBox, BoundingBoxes, DepthPoint, DepthPoints , Object, ObjectLocations
ImportError: cannot import name 'BoundingBox' from 'yolov8_ros_msgs.msg' (unknown location)
[yolov8_node-1] process has died [pid 64501, exit code 1, cmd /home/user/catkin_ws/devel/lib/yolov8_ros/yolo_ros.py __name:=yolov8_node __log:=/home/user/.ros/log/883ecf8a-85d2-11ee-b80d-1f706cd9acc6/yolov8_node-1.log].
log file: /home/user/.ros/log/883ecf8a-85d2-11ee-b80d-1f706cd9acc6/yolov8_node-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by qq44642754a** [comment]
You need to source the environment of your workspace, that is, ‘source devel/setup.bash’
